sudo: required

language: go

go:
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - tip

services:
    - docker

addons:
    mariadb: '10.1.24'
    hosts:
        - MARIADB

before_install:
    - go get github.com/golang/lint/golint
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/goimports

before_script:
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('mailboxdbs') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - mysql -h MARIADB -uroot -pmailboxdbs < ./sql/database.sql
    - mysql -h MARIADB -uroot -pmailboxdbs mailbox < ./sql/tables.sql

script:
    - sh ./goclean.sh
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.cov -service=travis-ci
    - sh ./build-base.sh
    - sh ./build-min.sh
    - docker images
    - docker run -it --rm toomore/mailbox:cmd sh -c "mailbox -h"
