sudo: required

language: go

go:
    - 1.10.x
    - 1.11.x
    - 1.12.x

env:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=linux GIMME_ARCH=amd64 GO111MODULE=on
    - GO111MODULE=on

services:
    - docker

addons:
    mariadb: '10.1.24'
    hosts:
        - MARIADB

before_install:
    - go get -v golang.org/x/lint/golint
    - go get -v golang.org/x/tools/cmd/goimports

install:
    - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=master bash)"

before_script:
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('mailboxdbs') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - mysql -h MARIADB -uroot -pmailboxdbs < ./sql/database.sql
    - mysql -h MARIADB -uroot -pmailboxdbs mailbox < ./sql/tables.sql

script:
    - go get -v ./...
    - test -z "$(gofmt -l -w ./     | tee /dev/stderr)"
    - test -z "$(goimports -l -w ./ | tee /dev/stderr)"
    - test -z "$(golint ./...       | tee /dev/stderr)"
    - go test -race ./campaign...
    - go test -race ./mails...
    - go test -race ./reader...
    - go test -race ./utils...
    - sh ./goclean.sh
    - go test -v -bench=Bench -benchmem -run='Bench' ./mails
    - go test -v -bench=Bench -benchmem -run='Bench' ./utils
    - sh ./build-base.sh
    - sh ./build-min.sh
    - docker images
    - docker run -it --rm toomore/mailbox:cmd sh -c "mailbox -h"

after_success:
    - go get -v github.com/mattn/goveralls
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.cov -service=travis-ci
