sudo: required

language: go

go:
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - tip

services:
    - docker

addons:
    mariadb: '10.1.24'

before_install:
    - go get github.com/golang/lint/golint
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/goimports

script:
    #- sh ./goclean.sh
    #- $HOME/gopath/bin/goveralls -coverprofile=coverage.cov -service=travis-ci
    #- bash <(curl -s https://codecov.io/bash)
    #- sh ./build-base.sh
    #- sh ./build-min.sh
    #- docker images
    #- docker run -it --rm toomore/mailbox:cmd sh -c "mailbox -h"
    - sh ./dev-run-mariadb.sh
    - docker ps --all
    - docker run -it --rm --link mailbox-mariadb:MARIADB -v $(pwd)/sql:/sql mariadb:10.1.24 sh -c "cat /ets/hosts; mysql -h MARIADB -uroot -pmailboxdbs < /sql/database.sql"
    - docker run -it --rm --link mailbox-mariadb:MARIADB -v $(pwd)/sql:/sql mariadb:10.1.24 sh -c "mysql -h MARIADB -uroot -pmailboxdbs < /sql/tables.sql"
    - sh ./dev-run-docker-travis.sh
